### ISSUE TITLE
Revisit os-perf setup

### ISSUE THREAD

**Issue by ckreibich** [zeek/zeek-benchmarker#14]
This is a broad push to improve the Zeek benchmarker setup to the point of allowing us to check performance evolution across meaningful checkpoint:
- [x] Establish comparability across meaningful sets of runs (e.g. for specific release tags): zeek/zeek-benchmarker#13, zeek/zeek-benchmarker#12, zeek/zeek-benchmarker#5
- [x] Expand set of tests conducted in a given run: zeek/zeek-benchmarker#8,  zeek/zeek-benchmarker#6
- [x] Basic infrastructure work: zeek/zeek-benchmarker#4, zeek/zeek-benchmarker#2

**Comment by awelzel** [comment]
I'm closing this. I don't have anything on my list to do for 6.1 or major in the near term future.
